
sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew build -x test

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/jFSTMerge/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-d3df9f7ff4ff6d62bca7c714b42d6ada0918dab8
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            